include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

formatter:
  page_width: 100

linter:
  rules:
    - always_declare_return_types
    - public_member_api_docs
    - prefer_single_quotes
    - unawaited_futures
